### ISSUE TITLE
Is it possible to snoop the Visual Studio designer?

### ISSUE THREAD

**Issue by DaveInCaz** [snoopwpf/snoopwpf#185]
I'm familiar with debugging the XDesProc process in a second instance of Visual Studio, but this doesn't seem to allow inspecting things at the WPF level as easily as Snoop does.

However when I run Snoop, even as admin, it never lists the XDesProc process or anything else that appears to be related to the XAML running in the designer of Visual Studio.

Is there any way to do this?

The specific use case I have in mind is debugging bound data being passed from design instances classes.

Thanks

**Comment by batzen** [comment]
In theory this should work. Will try this myself later.
Which version of Visual Studio and snoop are you using?

**Comment by DaveInCaz** [comment]
VS2019, the Snoop I have is 2.11.0.0.

Thanks

**Comment by batzen** [comment]
I just tried this myself.
Starting with some VS2019 version (i guess it's 16.6) there is no XDeskProc anymore and instead there is WpfSurface.
At least with WpfSurface you don't get much insight by using snoop because that application only seems to render an image and transfers that to visual studio.
In Visual Studio there is just this when looking at the designer view:
![image](https://user-images.githubusercontent.com/1971030/84805732-ff6e5500-b004-11ea-882e-a60286d6da88.png)

**Comment by DaveInCaz** [comment]
Hmm ... I do still see an XDesProc.exe running in Windows Task Manager. If you have a design-time exception in code-behind for instance, attaching to that process is often the best way to debug the issue, so I'm pretty sure it still always corresponds to the visible designer in VS.

Perhaps they changed the mechanism by which that process interacts with VS, and that's where WpfSurface comes in?

However I don't see any WpfSurface process running ... ?

**Comment by batzen** [comment]
Yeah, your idea sounded interesting. But snoop can't inspect in code image rendering ;-)

**Comment by DaveInCaz** [comment]
Thanks for looking into it.
