### ISSUE TITLE
Visual Tree and text value colors have black background

### ISSUE THREAD

**Issue by EgilSandfeld** [snoopwpf/snoopwpf#293]
Hi guys, first time Snoop user here.
Trying out the helper, when the visual window opens up after targeting Snoop, it shows black background behind the Visual Tree view (guessing) and some text values.

How can I rectify this? It's really hard to tell what it says as the text color is almost black as well.
Running Windows 10 Dark mode, but changed it to Light to see, but issue remained.

![image](https://user-images.githubusercontent.com/5029330/141673671-b4d8d790-eea0-42bc-8de0-2747aa4cc423.png)

**Comment by batzen** [comment]
Hi there.
Which version of Snoop are you using?
This looks like some application styles "bubble" to Snoop.

Could you try the upcoming version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/master/artifacts to see if the issue remains?

**Comment by EgilSandfeld** [comment]
Was using [Snoop 3.0.1](https://github.com/snoopwpf/snoopwpf/releases/tag/v3.0.1)
Still is an issue with Snoop.4.0.0-rc0376 unfortunately. 

It's my own app I'm debugging, and it seems this is the issue. I tested another random app that displayed fine in Snoop. 
Developing the app myself,I should be able to change any bubbling up colors, but do you happen to know which app styles it could be from?

**Comment by EgilSandfeld** [comment]
Ah solved it. The black background color in that screenshot was not fully black, so I could search the #0c0907 hex color string in my app xaml and removed those places. Works now, thank you.

![image](https://user-images.githubusercontent.com/5029330/141674465-cedbe5af-f984-4fe1-9293-f57230a668d7.png)

**Comment by batzen** [comment]
Well, if this still happens with the latest Snoop version it's a bug in Snoop as Snoop is supposed to not use application supplied style/resources etc. at all. The list on the right side, in your screenshot, also has wrong sizes for the rows etc.. Would be nice if you could test the version from the CI build i posted and report back if it still looks like your screenshot.
If it still looks like that i have to fix something in Snoop. 😉

**Comment by EgilSandfeld** [comment]
The last screenshot taken was using Snoop.4.0.0-rc0376. I updated to that from your link and installed into the existing installation folder, then opened.

Let me know if you need more info on the bug since I can reproduce it

**Comment by batzen** [comment]
Would it be possible for you to share the application you are snooping?
If it's not possible to share it publicly we can find a way to do it privately.
That would help a lot to find out why the styles are applied to Snoop.

**Comment by EgilSandfeld** [comment]
Sure thing, actually the older [public version 3.4.2](https://www.thedigitalraceengineer.com/download/) does it as well. Download that and open it, and Snoop should instantly show black background when attaching - #0c0907 in my case.

That color is used multiple places in the xaml code:
![image](https://user-images.githubusercontent.com/5029330/141839540-e9813497-87f9-44d5-946e-19312017d247.png)

**Comment by batzen** [comment]
Thanks. Will have a look and fix the issue as soon as i have some spare time.

**Comment by batzen** [comment]
Ok. I know what's causing the strange look, but i don't know how to prevent it yet.
It's caused by the presence of a style for `StackPanel` in the styles of your application.

I have, as the bug in Snoop obviously reveals, seen applications define a style for basic elements such as `StackPanel`.

I tried to fix it the usual way used in Snoop by setting the style for controls to `x:Null`, but that does not work in this case as Snoop does not define control templates for every control it uses, so as soon as there is a `StackPanel` being used the styles of your application apply.
This might be because there isn't a system/WPF defined default style for `StackPanel`.
Will be fun to figure out how to solve this ;-)

**Comment by EgilSandfeld** [comment]
Why not override default styles in Snoop? Basically fight fire with fire

**Comment by batzen** [comment]
Well that would mean, because the root cause is a quite strange behavior from WPF itself (see https://source.dot.net/#PresentationFramework/System/Windows/FrameworkElement.cs,904), even overwriting things like `ItemsPanelTemplate` everywhere.

As a rule of thumb i guess it's a bad idea to overwrite the default style for everything that does not inherit from `Control` or is a `FrameworkContentElement`. At least if it's a framework provided class.

Having to overwrite styles and control templates is one thing, but also having to overwrite things like `ItemsPanelTemplate`, basically everything that represents a template, is quite some work.
I fear i will have to do all that to fix this issue...
It will take me quite some time to do that, but i might already have to do that, at least most of it, to support a dark mode in Snoop.

**Comment by batzen** [comment]
@EgilSandfeld Could you try the latest version from the CI build? Your issue should hopefully be fixed there.

**Comment by batzen** [comment]
@EgilSandfeld I found and fixed a few more issues. Everything should be fine now.

**Comment by EgilSandfeld** [comment]
I can confirm it's fixed :) Well done, and thanks for a great product.

![image](https://user-images.githubusercontent.com/5029330/143830172-396e310c-cc9f-48f0-b7d4-70d2afee2609.png)
