### ISSUE TITLE
Snoop 3.0.0-alpha black magic?

### ISSUE THREAD

**Issue by znakeeye** [snoopwpf/snoopwpf#299]
I'm currently debugging a rare WPF binding bug (related to [this issue](https://stackoverflow.com/questions/34745847/why-are-relative-bindings-in-a-virtualized-data-grid-sometimes-not-resolved?rq=1)). In our project, we end up with broken bindings (due to `RelativeSource` bailing out).

Now, using a very specific version of Snoop, we are able to repair these bindings when selecting the item in the visual tree. Not with v3.0, not with v3.0.1. It has to be **this version**:

```
3.0.0-alpha.116+Branch.develop.Sha.0234efe39bf4b9faf62bad3dcfeeeaf389799af9
```

Any other version will **not** update the bindings of the selected item. Black magic, obviously.

**The question** is, do you remember what special tweaks you had in this version? Also, how do we get hold of the source code for it?

Here's an image of the selection I'm referring to. When I click `ListBoxItem` it magically fixes the broken bindings. Which API is being used? Well, it should be somewhere in that special version 😄 

![image](https://user-images.githubusercontent.com/958469/145427319-feed2e1c-7cdf-4711-a1e8-f9eb377b1184.png)

Your help is greatly appreciated!

**Comment by batzen** [comment]
That might be, because older versions of Snoop re-assigned bindings which had errors, to be able to grab the error message.
This was happening implicitly and caused some bindings to be fixed, when you tried to investigate.
Newer versions of Snoop changed this to be explicit by offering a button on the binding/property that has errors.
That way it's more obvious if Snoop fixed the binding while trying to resolve the error.

Version 4 will automatically collect most binding errors through the new diagnostics features built into WPF itself which, in most causes, does not require re-assignments of bindings.

**Comment by batzen** [comment]
The code responsible for this is, starting with version 4, in https://github.com/snoopwpf/snoopwpf/blob/fa803628b07b21919bff0e68438306753eb74b26/Snoop.Core/Infrastructure/Diagnostics/BindingDiagnosticHelper.cs#L67

**Comment by znakeeye** [comment]
Aha! Many thanks! :)
