### ISSUE TITLE
Missing TextBlock.LineHeight

### ISSUE THREAD

**Issue by greuelpirat** [snoopwpf/snoopwpf#394]
I attach Snoop `5.0.0` to our WPF app (using `net48`). So far everything is fine. But now I found that I can not read/set [TextBlock.LineHeight](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock.lineheight?view=netframework-4.8) of some ordinary TextBlock, any idea why?

![image](https://user-images.githubusercontent.com/16866222/211483467-25144f37-73bd-4329-abc7-51d036192835.png)

Thank you!

**Comment by batzen** [comment]
That's because it's hidden by default.

Snoop has a list of uncommon types/properties to prevent the property grid from being flooded.
`LineHeight` is from the type `Block` and that type is considered uncommon and thus not shown by default.

You can show uncommon properties by activating the small "U" above the property grid.

**Comment by greuelpirat** [comment]
Oh, thank you! that worked!

**Comment by batzen** [comment]
Ansonsten zufrieden mit Version 5?
Für Feedback bin ich immer dankbar 😁

**Comment by greuelpirat** [comment]
Ja! Ich finde Snoop allgemein sehr gut! Allein dass man direkt Methods aufrufen kann ich großartig!

Muss aber gestehen, dass mich der Dark-Mode etwas geflasht hab. Den habe ich abgeschaltet. Kann nicht genau sagen warum, aber ich finde den unangenehm, obwohl ich sonst viele Apps (wie z.b. github) im Dark-Theme nutze.
