### ISSUE TITLE
Feature Request: Option to snoop without activating snoop on global shortcut

### ISSUE THREAD

**Issue by MillerMark** [snoopwpf/snoopwpf#414]
I have an app that presents UI that I want to snoop, but that UI disappears as soon as I press the global shortcut because the app I'm snooping hides the UI when it deactivates. An option to snoop without deactivating (or a shortcut to snoop what's under the mouse without deactivating the active application) would be useful.

**Comment by batzen** [comment]
That's already implemented. 😉

Just start Snoop, focus your desired app and hit CTRL + WIN + ALT + F12

You can also configure that shortcut in the global settings for Snoop.

**Comment by MillerMark** [comment]
That doesn't work for me. Pressing that global shortcut causes the app that has focus to **deactivate**, and when the app I want to investigate loses focus it **closes the window I'm investigating**. So what I'm asking for is a way to get snoop to allow me to investigate what's under the mouse in the active window, *without* deactivating that active window (maybe by taking a snapshot or by simply always showing me what's under the mouse?).

**Comment by batzen** [comment]
Which application are you trying to investigate?

Maybe I better understand your issue/requirement if I can try it myself.

**Comment by BButner** [comment]
@batzen It sounds like he's saying the following:

1. Open some sort of popup (Like the WPF Context Menu)
2. Hit the Global Hotkey
3. See that the Context Menu closes

This is happening because when you open the Context Menu, if that Context Menu loses focus it automatically closes. When you hit the Snoop Global Hotkey, its activating and causing the Context Menu to lose focus, thus the Context Menu closes when you're trying to Snoop it.

I believe he's asking if you can activate Snoop, without Windows automatically switching focus to the Snoop window itself.

**Comment by batzen** [comment]
@MillerMark I hope the changes i made are you expected and what @BButner described.
Could you test it and give some feedback?
